kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-watcher.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-watcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-watcher.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
