apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-watcher.fullname" . }}
data:
  config.yaml: |-
    {{ if .Values.watcher.resources -}}
    resource: {{ .Values.watcher.resources | toYaml | nindent 6 }}
    {{- end }}
    {{ if .Values.watcher.trigger -}}
    trigger: {{ .Values.watcher.trigger | toYaml | nindent 6 }}
    {{- else }}
    trigger: {}
    {{- end }}